export const nodes = [
    {
      id: "1",
      data: { label: "Auth" },
      position: { x: 0, y: 0 },
      type: "input",
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "2",
      data: { label: "SignUp" },
      position: { x: 200, y: -100 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "3",
      data: { label: "SignIn" },
      position: { x: 200, y: 100 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "4",
      data: { label: "New Email, Password & Other Details" },
      position: { x: 400, y: -109 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "5",
      data: { label: "Email & Password Login" },
      position: { x: 400, y: 100 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "6",
      data: { label: "Option to Opt for TOTP" },
      style: {
        backgroundColor: `#049ba2`,
        color: `#fff`,
        borderRadius: `3px`,
        textAlign: "center",
      },
      position: { x: 1200, y: -100 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "7",
      data: { label: "Check if user opted for a TOTP" },
      position: { x: 600, y: 91 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "8",
      data: { label: "Yes" },
      position: { x: 1400, y: -130 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "9",
      data: { label: "No" },
      position: { x: 1400, y: -70 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "10",
      data: { label: "Yes" },
      position: { x: 800, y: 80 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "11",
      data: { label: "No" },
      position: { x: 800, y: 130 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "12",
      data: { label: "Normal Email Based 2fa Verification" },
      position: { x: 600, y: -109 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "13",
      data: { label: "TOTP based verification starts" },
      position: { x: 1600, y: -150 },
      style: {
        backgroundColor: `#049ba2`,
        color: `#fff`,
        borderRadius: `3px`,
        textAlign: "center",
      },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "14",
      data: { label: "Normal Email Based 2fa Verification" },
      position: { x: 1000, y: 130 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "15",
      data: { label: "TOTP based verification starts" },
      position: { x: 1000, y: 60 },
      style: {
        backgroundColor: `#049ba2`,
        color: `#fff`,
        borderRadius: `3px`,
        textAlign: "center",
      },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "16",
      data: { label: "QR Code generated for Authenticator App" },
      position: { x: 1800, y: -150 },
      style: {
        backgroundColor: `#049ba2`,
        color: `#fff`,
        borderRadius: `3px`,
        textAlign: "center",
      },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "17",
      data: { label: "Email OTP Verified" },
      position: { x: 800, y: -100 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "18",
      data: { label: "Add 6 Digit OTP from Authenticator App" },
      position: { x: 1200, y: 60 },
      style: {
        backgroundColor: `#049ba2`,
        color: `#fff`,
        borderRadius: `3px`,
        textAlign: "center",
      },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "19",
      data: { label: "Email OTP Verified" },
      position: { x: 1200, y: 139 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "20",
      data: { label: "Add 6 Digit OTP from Authenticator App" },
      position: { x: 2000, y: -150 },
      style: {
        backgroundColor: `#049ba2`,
        color: `#fff`,
        borderRadius: `3px`,
        textAlign: "center",
      },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "21",
      data: { label: "Main UI / Setting User Preferrences" },
      position: { x: 1000, y: -109 },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "22",
      data: { label: "Success" },
      position: { x: 1400, y: 139 },
      sourcePosition:"left",
      targetPosition:"left",
    },
    {
      id: "23",
      data: { label: "OTP Verification" },
      position: { x: 1400, y:69 },
      style: {
        backgroundColor: `#049ba2`,
        color: `#fff`,
        borderRadius: `3px`,
        textAlign: "center",
      },
      sourcePosition:"right",
      targetPosition:"left",
    },
    {
      id: "24",
      data: { label: "Success" },
      position: { x: 2200, y:-141 },
      sourcePosition:"left",
      targetPosition:"left",
    },
    {
      id: "25",
      data: { label: "Success" },
      position: { x: 1600, y:69 },
      sourcePosition:"left",
      targetPosition:"left",
    },
    {
      id: "26",
      data: { label: "No Change / Email Based" },
      position: { x: 1600, y:-69 },
      sourcePosition:"left",
      targetPosition:"left",
    },
]