import React from 'react';
import TOTPImage from '../assets/totp.webp';

const WhatIsTOTP = () => {
  return (
    <div className="flex flex-col items-start justify-start p-6 space-y-6">
      <h1 className="text-4xl font-bold">What is TOTP?</h1>
      <p className="text-lg leading-relaxed">
        TOTP stands for Time-based One-Time Password. It is a temporary passcode, generated by an algorithm, that uses the current time as one of its factors. This passcode is valid for a short period of time and is widely used as a two-factor authentication (2FA) method to enhance security.
      </p>
      
      <h2 className="text-3xl font-semibold">How TOTP Works</h2>
      <p className="text-lg leading-relaxed">
        TOTP algorithms generate a unique, time-based passcode using a shared secret key and the current time. This secret key is usually provided in the form of a QR code or a secret key during the initial setup. The TOTP algorithm typically follows these steps:
      </p>
      <ol className="list-decimal list-inside space-y-2 text-lg leading-relaxed">
        <li>The user sets up TOTP by scanning a QR code or entering a secret key in their authenticator app (e.g., Google Authenticator).</li>
        <li>The authenticator app generates a one-time password using the shared secret key and the current timestamp.</li>
        <li>When logging in, the user enters the generated TOTP code along with their password.</li>
        <li>The server verifies the TOTP code by generating its own code using the same secret key and comparing it with the user's input.</li>
        <li>If the codes match, the user is authenticated.</li>
      </ol>
      
      <h2 className="text-3xl font-semibold">Advantages of TOTP</h2>
      <p className="text-lg leading-relaxed">
        TOTP offers several advantages as a two-factor authentication method:
      </p>
      <ul className="list-disc list-inside space-y-2 text-lg leading-relaxed">
        <li><strong>Enhanced Security:</strong> TOTP adds an extra layer of security by requiring a time-based code in addition to the password.</li>
        <li><strong>Time-limited:</strong> The generated codes are valid for a short period (usually 30 seconds), reducing the risk of unauthorized access.</li>
        <li><strong>Offline Verification:</strong> The TOTP codes are generated locally on the user's device without requiring an internet connection.</li>
        <li><strong>Standardized:</strong> TOTP is based on the widely adopted standard specified in RFC 6238, making it compatible with various services and applications.</li>
      </ul>
      
      <h2 className="text-3xl font-semibold">Example: Setting Up TOTP</h2>
      <p className="text-lg leading-relaxed">
        Let's walk through an example of setting up TOTP using an authenticator app:
      </p>
      <ol className="list-decimal list-inside space-y-2 text-lg leading-relaxed">
        <li>Install an authenticator app on your smartphone, such as Google Authenticator or Authy.</li>
        <li>Navigate to the security settings of the service you want to secure (e.g., a banking app or an email provider) and choose the option to set up TOTP.</li>
        <li>Scan the provided QR code using the authenticator app or manually enter the secret key.</li>
        <li>The authenticator app will start generating one-time passwords based on the shared secret key and the current time.</li>
        <li>Enter the TOTP code displayed in the app into the service's setup page to complete the setup process.</li>
      </ol>
      <div className="flex items-center justify-center mt-4">
        <img src={TOTPImage} alt="TOTP Example" className="w-full max-w-xl shadow-lg rounded-lg" />
      </div>
      
      <h2 className="text-3xl font-semibold">Common Use Cases</h2>
      <p className="text-lg leading-relaxed">
        TOTP is widely used in various applications and services, including:
      </p>
      <ul className="list-disc list-inside space-y-2 text-lg leading-relaxed">
        <li>Securing online accounts (e.g., email, social media, and banking)</li>
        <li>VPN authentication</li>
        <li>Enterprise security for accessing internal systems</li>
        <li>Two-factor authentication for developer tools and platforms (e.g., GitHub, AWS)</li>
      </ul>
      
      <h2 className="text-3xl font-semibold">Conclusion</h2>
      <p className="text-lg leading-relaxed">
        TOTP is an effective and widely used method for enhancing security through two-factor authentication. By generating time-based one-time passwords, it adds an extra layer of protection, making it significantly harder for unauthorized users to gain access to your accounts and systems.
      </p>
    </div>
  );
};

export default WhatIsTOTP;
